### ISSUE TITLE
THIS CODE IS NOT WORKING ANYMORE 

### ISSUE THREAD

**Issue by shanidsulthan** [xanpj/ShazamDownloader#1]
HELLO DEVELOPER I REALLY ENJOYED THIS CODE FOR FEW MONTHS 
THANK YOU FOR MAKING THIS CODE 

I AM SAYING THAT NOW IT IS NOT WORKING 
AN ERROR IS CAUSING THE PROBLEM 

AS USUAL WHEN I PUT THIS CODE IN CONSOLE AN ERROR POPS UP

ERROR AS MENTIONED BELOW 

VM107:146 Uncaught TypeError: Cannot read property 'textContent' of undefined
    at <anonymous>:146:77
(anonymous) @ VM107:146

I HOPE YOU WILL MODIFY YOUR CODE TO OVERCOME THIS ERROR

I THINK THAT SHAZAM WEBSITE HAS MADE CHANGES TO THEIR WEBAPP

**Comment by xanpj** [comment]
Thanks for the notice! Will look into it once I find time.

**Comment by shanidsulthan** [comment]
> Thanks for the notice! Will look into it once I find time.

SIR ANY POSITIVE NEWS?

**Comment by xanpj** [comment]
I will close this issue, because you can now download from shazam via the "Download to CSV" button.
